---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <vartotojo vardas>
  namespace: <vartotojo vardas>

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: <vartotojo vardas>-user-full-access
  namespace: <vartotojo vardas>
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: <vartotojo vardas>-user-view
  namespace: <vartotojo vardas>
subjects:
- kind: ServiceAccount
  name: <vartotojo vardas>
  namespace: <vartotojo vardas>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: <vartotojo vardas>-user-full-access